/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyChildOne {
    }
    interface MyChildTwo {
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLMyChildOneElement extends Components.MyChildOne, HTMLStencilElement {
    }
    var HTMLMyChildOneElement: {
        prototype: HTMLMyChildOneElement;
        new (): HTMLMyChildOneElement;
    };
    interface HTMLMyChildTwoElement extends Components.MyChildTwo, HTMLStencilElement {
    }
    var HTMLMyChildTwoElement: {
        prototype: HTMLMyChildTwoElement;
        new (): HTMLMyChildTwoElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-child-one": HTMLMyChildOneElement;
        "my-child-two": HTMLMyChildTwoElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyChildOne {
    }
    interface MyChildTwo {
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "my-child-one": MyChildOne;
        "my-child-two": MyChildTwo;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-child-one": LocalJSX.MyChildOne & JSXBase.HTMLAttributes<HTMLMyChildOneElement>;
            "my-child-two": LocalJSX.MyChildTwo & JSXBase.HTMLAttributes<HTMLMyChildTwoElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
